version: 1.4.0
env:
  - JENKINS_NODE_WIN: "CDA-VS22-SVC"
  - SLACK_QUANTUM_BUILD_CHANNEL : "#dynamo-jenkinsbuild"
  - SLACK_QUANTUM_BUILD_CREDENTIAL_ID : "slack-notify-token"
  - MAIL_QUANTUM_BUILD_RECIPIENT : "dynamo.dev@autodesk.com"

check_changelog_updated_on_pr: false
pipeline_os: "Windows"
force_slack_notification : true
language: csharp

schedule :
  cron_schedule : once_a_week

build:
  -
    scripts:
      - dotnet build --configuration Release IronPython3Extension.sln

ci_test:
  tests:    
    -
      scripts:
        - dotnet coverage collect "dotnet test --no-build --configuration Release IronPython3Extension.sln --filter \"TestCategory!=Failure\" --logger:junit  --logger:trx" -f xml -o "coverage.xml"
  test_report_dir: "IronPython3Tests/TestResults"
  test_report_pattern:
    format: "junit"
    pattern: "*.xml"

code_analysis:
  sonarqube:
    useDotnetSonarScanner: true
    scanOnAnyBranch: true
    coverage_reports:
      - coverage.xml

soc2:
  harmony:
    allow_branches:
      - master
    hidden_email_list: dynamo_ws_access
    fail_on_audit_failure: false
    third_party_lib_paths:
      - package_output

deployment:
  -  
    type: sign
    files_to_sign:
        - package_output\DSIronPython3\bin\DSIronPython3Empty.dll
        - package_output\DSIronPython3\extra\python3eval.dll
        - package_output\DSIronPython3\extra\IronPython3Extension.dll
 
  -
    type: artifacts
    publish_to_jenkins: true
    publish_to_artifactory: false
    publish_to_package_manager: true
    use_dev_pm: false
    allow_branches: ".*"
    outputs:
      - "DSIronPython3Package.zip"